### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by boriscy** [emerleite/mongox#3]
You can set timeout on the config but it's not working it uses te default 5000

**Comment by boriscy** [comment]
I have been digging this issue and I have made some changes to the default timeout for the socket, in the line https://github.com/emerleite/mongox/blob/master/lib/mongo/connection.ex#L73
you can see in it makes a GenServer.call with it's default 5000, I have made small change to pass in the `opts[:timeout]` but it seems that most of the time it fails after **10 seconds**, have also changed in `Mongo.Pool` to set `@timeout 20000` to see if that was the error but this doesn't seem to affect

**Comment by bernardolins** [comment]
Closed by #4
